// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.cambrian.cambrian_ios_camera

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class SessionState(val raw: Int) {
  OPENING(0),
  STREAMING(1),
  RECOVERING(2),
  PAUSED(3),
  ERROR(4),
  CLOSED(5),
  INTERRUPTED(6);

  companion object {
    fun ofRaw(raw: Int): SessionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class StreamId(val raw: Int) {
  NATURAL(0),
  PROCESSED(1),
  TRACKER(2);

  companion object {
    fun ofRaw(raw: Int): StreamId? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CameraPermissionStatus(val raw: Int) {
  NOT_DETERMINED(0),
  DENIED(1),
  RESTRICTED(2),
  AUTHORIZED(3);

  companion object {
    fun ofRaw(raw: Int): CameraPermissionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PhotosDestination(val raw: Int) {
  NONE(0),
  COPY(1),
  MOVE(2);

  companion object {
    fun ofRaw(raw: Int): PhotosDestination? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CameraMode(val raw: Int) {
  AUTO(0),
  MANUAL(1);

  companion object {
    fun ofRaw(raw: Int): CameraMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WhiteBalanceMode(val raw: Int) {
  AUTO(0),
  LOCKED(1),
  MANUAL(2);

  companion object {
    fun ofRaw(raw: Int): WhiteBalanceMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RecordingStateKind(val raw: Int) {
  IDLE(0),
  RECORDING(1),
  FINALIZING(2);

  companion object {
    fun ofRaw(raw: Int): RecordingStateKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CameraErrorCode(val raw: Int) {
  CAMERA_NOT_FOUND(0),
  CAMERA_IN_USE(1),
  PERMISSION_DENIED(2),
  CAMERA_ACCESS_ERROR(3),
  CAMERA_DISCONNECTED(4),
  CONFIGURATION_FAILED(5),
  CAPTURE_FAILURE(6),
  RECORDING_START_FAILED(7),
  RECORDING_FAILED(8),
  RECORDING_TRUNCATED(9),
  FRAME_STALL(10),
  MAX_RETRIES_EXCEEDED(11),
  UNKNOWN_ERROR(12),
  SETTINGS_CONFLICT(13),
  INVALID_FORMAT(14),
  FPS_DEGRADED(15),
  AE_CONVERGENCE_TIMEOUT(16),
  INVALID_STATE(17),
  HARDWARE_ERROR(18),
  NOT_OPEN(19);

  companion object {
    fun ofRaw(raw: Int): CameraErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PSize (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PSize {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return PSize(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PRect (
  val x: Long,
  val y: Long,
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PRect {
      val x = pigeonVar_list[0] as Long
      val y = pigeonVar_list[1] as Long
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      return PRect(x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpenConfiguration (
  val cameraId: String? = null,
  val captureResolution: PSize? = null,
  val cropRegion: PRect? = null,
  val initialSettings: CameraSettings? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenConfiguration {
      val cameraId = pigeonVar_list[0] as String?
      val captureResolution = pigeonVar_list[1] as PSize?
      val cropRegion = pigeonVar_list[2] as PRect?
      val initialSettings = pigeonVar_list[3] as CameraSettings?
      return OpenConfiguration(cameraId, captureResolution, cropRegion, initialSettings)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cameraId,
      captureResolution,
      cropRegion,
      initialSettings,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SessionCapabilities (
  val supportedSizes: List<PSize?>,
  val previewTextureId: Long,
  val naturalTextureId: Long,
  val activeCaptureResolution: PSize,
  val activeCropRegion: PRect,
  val streamPixelFormat: String,
  val isoMin: Double,
  val isoMax: Double,
  val exposureDurationMinNs: Long,
  val exposureDurationMaxNs: Long,
  val focusMin: Double,
  val focusMax: Double,
  val zoomMin: Double,
  val zoomMax: Double,
  val evMin: Double,
  val evMax: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SessionCapabilities {
      val supportedSizes = pigeonVar_list[0] as List<PSize?>
      val previewTextureId = pigeonVar_list[1] as Long
      val naturalTextureId = pigeonVar_list[2] as Long
      val activeCaptureResolution = pigeonVar_list[3] as PSize
      val activeCropRegion = pigeonVar_list[4] as PRect
      val streamPixelFormat = pigeonVar_list[5] as String
      val isoMin = pigeonVar_list[6] as Double
      val isoMax = pigeonVar_list[7] as Double
      val exposureDurationMinNs = pigeonVar_list[8] as Long
      val exposureDurationMaxNs = pigeonVar_list[9] as Long
      val focusMin = pigeonVar_list[10] as Double
      val focusMax = pigeonVar_list[11] as Double
      val zoomMin = pigeonVar_list[12] as Double
      val zoomMax = pigeonVar_list[13] as Double
      val evMin = pigeonVar_list[14] as Double
      val evMax = pigeonVar_list[15] as Double
      return SessionCapabilities(supportedSizes, previewTextureId, naturalTextureId, activeCaptureResolution, activeCropRegion, streamPixelFormat, isoMin, isoMax, exposureDurationMinNs, exposureDurationMaxNs, focusMin, focusMax, zoomMin, zoomMax, evMin, evMax)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportedSizes,
      previewTextureId,
      naturalTextureId,
      activeCaptureResolution,
      activeCropRegion,
      streamPixelFormat,
      isoMin,
      isoMax,
      exposureDurationMinNs,
      exposureDurationMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evMin,
      evMax,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraSettings (
  val isoMode: CameraMode? = null,
  val iso: Long? = null,
  val exposureMode: CameraMode? = null,
  val exposureTimeNs: Long? = null,
  val focusMode: CameraMode? = null,
  val focusDistance: Double? = null,
  val wbMode: WhiteBalanceMode? = null,
  val wbGainR: Double? = null,
  val wbGainG: Double? = null,
  val wbGainB: Double? = null,
  val zoomRatio: Double? = null,
  val evCompensation: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraSettings {
      val isoMode = pigeonVar_list[0] as CameraMode?
      val iso = pigeonVar_list[1] as Long?
      val exposureMode = pigeonVar_list[2] as CameraMode?
      val exposureTimeNs = pigeonVar_list[3] as Long?
      val focusMode = pigeonVar_list[4] as CameraMode?
      val focusDistance = pigeonVar_list[5] as Double?
      val wbMode = pigeonVar_list[6] as WhiteBalanceMode?
      val wbGainR = pigeonVar_list[7] as Double?
      val wbGainG = pigeonVar_list[8] as Double?
      val wbGainB = pigeonVar_list[9] as Double?
      val zoomRatio = pigeonVar_list[10] as Double?
      val evCompensation = pigeonVar_list[11] as Long?
      return CameraSettings(isoMode, iso, exposureMode, exposureTimeNs, focusMode, focusDistance, wbMode, wbGainR, wbGainG, wbGainB, zoomRatio, evCompensation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistance,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      evCompensation,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProcessingParameters (
  val brightness: Double,
  val contrast: Double,
  val saturation: Double,
  val blackR: Double,
  val blackG: Double,
  val blackB: Double,
  val gamma: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProcessingParameters {
      val brightness = pigeonVar_list[0] as Double
      val contrast = pigeonVar_list[1] as Double
      val saturation = pigeonVar_list[2] as Double
      val blackR = pigeonVar_list[3] as Double
      val blackG = pigeonVar_list[4] as Double
      val blackB = pigeonVar_list[5] as Double
      val gamma = pigeonVar_list[6] as Double
      return ProcessingParameters(brightness, contrast, saturation, blackR, blackG, blackB, gamma)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      brightness,
      contrast,
      saturation,
      blackR,
      blackG,
      blackB,
      gamma,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StreamConfiguration (
  val activeCaptureResolution: PSize,
  val activeCropRegion: PRect
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamConfiguration {
      val activeCaptureResolution = pigeonVar_list[0] as PSize
      val activeCropRegion = pigeonVar_list[1] as PRect
      return StreamConfiguration(activeCaptureResolution, activeCropRegion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      activeCaptureResolution,
      activeCropRegion,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FrameResult (
  val iso: Long? = null,
  val exposureTimeNs: Long? = null,
  val focusDistance: Double? = null,
  val wbGainR: Double? = null,
  val wbGainG: Double? = null,
  val wbGainB: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FrameResult {
      val iso = pigeonVar_list[0] as Long?
      val exposureTimeNs = pigeonVar_list[1] as Long?
      val focusDistance = pigeonVar_list[2] as Double?
      val wbGainR = pigeonVar_list[3] as Double?
      val wbGainG = pigeonVar_list[4] as Double?
      val wbGainB = pigeonVar_list[5] as Double?
      return FrameResult(iso, exposureTimeNs, focusDistance, wbGainR, wbGainG, wbGainB)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      iso,
      exposureTimeNs,
      focusDistance,
      wbGainR,
      wbGainG,
      wbGainB,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecordingOptions (
  val bitrateBps: Long? = null,
  val fps: Long? = null,
  val outputPath: String? = null,
  val photosDestination: PhotosDestination
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecordingOptions {
      val bitrateBps = pigeonVar_list[0] as Long?
      val fps = pigeonVar_list[1] as Long?
      val outputPath = pigeonVar_list[2] as String?
      val photosDestination = pigeonVar_list[3] as PhotosDestination
      return RecordingOptions(bitrateBps, fps, outputPath, photosDestination)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bitrateBps,
      fps,
      outputPath,
      photosDestination,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecordingStart (
  val uri: String,
  val displayName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecordingStart {
      val uri = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      return RecordingStart(uri, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      displayName,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecordingStateValue (
  val kind: RecordingStateKind,
  val lastUri: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecordingStateValue {
      val kind = pigeonVar_list[0] as RecordingStateKind
      val lastUri = pigeonVar_list[1] as String?
      return RecordingStateValue(kind, lastUri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      lastUri,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RgbSample (
  val r: Double,
  val g: Double,
  val b: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RgbSample {
      val r = pigeonVar_list[0] as Double
      val g = pigeonVar_list[1] as Double
      val b = pigeonVar_list[2] as Double
      return RgbSample(r, g, b)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      r,
      g,
      b,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CalibrationResult (
  val before: RgbSample,
  val after: RgbSample,
  val converged: Boolean,
  val iterations: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CalibrationResult {
      val before = pigeonVar_list[0] as RgbSample
      val after = pigeonVar_list[1] as RgbSample
      val converged = pigeonVar_list[2] as Boolean
      val iterations = pigeonVar_list[3] as Long
      return CalibrationResult(before, after, converged, iterations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      before,
      after,
      converged,
      iterations,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraError (
  val code: CameraErrorCode,
  val message: String,
  val isFatal: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraError {
      val code = pigeonVar_list[0] as CameraErrorCode
      val message = pigeonVar_list[1] as String
      val isFatal = pigeonVar_list[2] as Boolean
      return CameraError(code, message, isFatal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      isFatal,
    )
  }
}
private open class cambrian_ios_camera_apiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SessionState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          StreamId.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraPermissionStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PhotosDestination.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraMode.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WhiteBalanceMode.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RecordingStateKind.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraErrorCode.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PSize.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PRect.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenConfiguration.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionCapabilities.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraSettings.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProcessingParameters.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamConfiguration.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FrameResult.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecordingOptions.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecordingStart.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecordingStateValue.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RgbSample.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CalibrationResult.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SessionState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is StreamId -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is CameraPermissionStatus -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is PhotosDestination -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is CameraMode -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is WhiteBalanceMode -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is RecordingStateKind -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is CameraErrorCode -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is PSize -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PRect -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is OpenConfiguration -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is SessionCapabilities -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is CameraSettings -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is ProcessingParameters -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is StreamConfiguration -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is FrameResult -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is RecordingOptions -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is RecordingStart -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is RecordingStateValue -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is RgbSample -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is CalibrationResult -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is CameraError -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val cambrian_ios_camera_apiPigeonMethodCodec = StandardMethodCodec(cambrian_ios_camera_apiPigeonCodec());


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraEngineHostApi {
  fun open(configuration: OpenConfiguration?, callback: (Result<SessionCapabilities>) -> Unit)
  fun close(callback: (Result<Unit>) -> Unit)
  fun currentSettings(callback: (Result<CameraSettings?>) -> Unit)
  fun currentProcessingParameters(callback: (Result<ProcessingParameters?>) -> Unit)
  fun updateSettings(settings: CameraSettings, callback: (Result<Unit>) -> Unit)
  fun setResolution(size: PSize, callback: (Result<Unit>) -> Unit)
  fun setProcessingParams(params: ProcessingParameters, callback: (Result<Unit>) -> Unit)
  fun setCropRegion(rect: PRect, callback: (Result<Unit>) -> Unit)
  fun captureImage(outputPath: String?, photosDestination: PhotosDestination, callback: (Result<String>) -> Unit)
  fun captureNaturalPicture(outputPath: String?, photosDestination: PhotosDestination, callback: (Result<String>) -> Unit)
  fun startRecording(options: RecordingOptions, callback: (Result<RecordingStart>) -> Unit)
  fun stopRecording(callback: (Result<String>) -> Unit)
  fun calibrateWhiteBalance(callback: (Result<CalibrationResult>) -> Unit)
  fun calibrateBlackBalance(callback: (Result<CalibrationResult>) -> Unit)
  fun createPreviewTexture(stream: StreamId, callback: (Result<Long>) -> Unit)
  fun destroyPreviewTexture(textureId: Long, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by CameraEngineHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      cambrian_ios_camera_apiPigeonCodec()
    }
    /** Sets up an instance of `CameraEngineHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraEngineHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as OpenConfiguration?
            api.open(configurationArg) { result: Result<SessionCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.close{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.currentSettings{ result: Result<CameraSettings?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentProcessingParameters$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.currentProcessingParameters{ result: Result<ProcessingParameters?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.updateSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as CameraSettings
            api.updateSettings(settingsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setResolution$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sizeArg = args[0] as PSize
            api.setResolution(sizeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setProcessingParams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as ProcessingParameters
            api.setProcessingParams(paramsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setCropRegion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val rectArg = args[0] as PRect
            api.setCropRegion(rectArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.captureImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val outputPathArg = args[0] as String?
            val photosDestinationArg = args[1] as PhotosDestination
            api.captureImage(outputPathArg, photosDestinationArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.captureNaturalPicture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val outputPathArg = args[0] as String?
            val photosDestinationArg = args[1] as PhotosDestination
            api.captureNaturalPicture(outputPathArg, photosDestinationArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.startRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as RecordingOptions
            api.startRecording(optionsArg) { result: Result<RecordingStart> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.stopRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopRecording{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.calibrateWhiteBalance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.calibrateWhiteBalance{ result: Result<CalibrationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.calibrateBlackBalance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.calibrateBlackBalance{ result: Result<CalibrationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.createPreviewTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val streamArg = args[0] as StreamId
            api.createPreviewTexture(streamArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.destroyPreviewTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            api.destroyPreviewTexture(textureIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PermissionsHostApi {
  fun cameraPermissionStatus(callback: (Result<CameraPermissionStatus>) -> Unit)
  fun requestCameraPermission(callback: (Result<CameraPermissionStatus>) -> Unit)

  companion object {
    /** The codec used by PermissionsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      cambrian_ios_camera_apiPigeonCodec()
    }
    /** Sets up an instance of `PermissionsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PermissionsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.PermissionsHostApi.cameraPermissionStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cameraPermissionStatus{ result: Result<CameraPermissionStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_ios_camera.PermissionsHostApi.requestCameraPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestCameraPermission{ result: Result<CameraPermissionStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PigeonStreamHandler<T>(
    val wrapper: PigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }
  
  fun endOfStream() { 
    sink.endOfStream()
  }
}
      
abstract class StreamStateStreamHandler : PigeonEventChannelWrapper<SessionState> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamStateStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamState"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonStreamHandler<SessionState>(streamHandler)
      EventChannel(messenger, channelName, cambrian_ios_camera_apiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class StreamErrorsStreamHandler : PigeonEventChannelWrapper<CameraError> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamErrorsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamErrors"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonStreamHandler<CameraError>(streamHandler)
      EventChannel(messenger, channelName, cambrian_ios_camera_apiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class StreamStreamConfigurationsStreamHandler : PigeonEventChannelWrapper<StreamConfiguration> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamStreamConfigurationsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamStreamConfigurations"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonStreamHandler<StreamConfiguration>(streamHandler)
      EventChannel(messenger, channelName, cambrian_ios_camera_apiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class StreamFrameResultsStreamHandler : PigeonEventChannelWrapper<FrameResult> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamFrameResultsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamFrameResults"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonStreamHandler<FrameResult>(streamHandler)
      EventChannel(messenger, channelName, cambrian_ios_camera_apiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class StreamRecordingStatesStreamHandler : PigeonEventChannelWrapper<RecordingStateValue> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamRecordingStatesStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamRecordingStates"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonStreamHandler<RecordingStateValue>(streamHandler)
      EventChannel(messenger, channelName, cambrian_ios_camera_apiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
