// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum SessionState: Int {
  case opening = 0
  case streaming = 1
  case recovering = 2
  case paused = 3
  case error = 4
  case closed = 5
  case interrupted = 6
}

enum StreamId: Int {
  case primary = 0
  case tracker = 1
}

enum CameraPermissionStatus: Int {
  case notDetermined = 0
  case denied = 1
  case restricted = 2
  case authorized = 3
}

enum PhotosDestination: Int {
  case none = 0
  case copy = 1
  case move = 2
}

enum CameraMode: Int {
  case auto = 0
  case manual = 1
}

enum WhiteBalanceMode: Int {
  case auto = 0
  case locked = 1
  case manual = 2
}

enum RecordingStateKind: Int {
  case idle = 0
  case recording = 1
  case finalizing = 2
}

enum CameraErrorCode: Int {
  case cameraNotFound = 0
  case cameraInUse = 1
  case permissionDenied = 2
  case cameraAccessError = 3
  case cameraDisconnected = 4
  case configurationFailed = 5
  case captureFailure = 6
  case recordingStartFailed = 7
  case recordingFailed = 8
  case recordingTruncated = 9
  case frameStall = 10
  case maxRetriesExceeded = 11
  case unknownError = 12
  case settingsConflict = 13
  case invalidFormat = 14
  case fpsDegraded = 15
  case aeConvergenceTimeout = 16
  case invalidState = 17
  case hardwareError = 18
  case notOpen = 19
  case calibrationFailed = 20
}

/// Generated class from Pigeon that represents data sent in messages.
struct PSize {
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PSize? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64

    return PSize(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PRect {
  var x: Int64
  var y: Int64
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PRect? {
    let x = pigeonVar_list[0] as! Int64
    let y = pigeonVar_list[1] as! Int64
    let width = pigeonVar_list[2] as! Int64
    let height = pigeonVar_list[3] as! Int64

    return PRect(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpenConfiguration {
  var cameraId: String? = nil
  var captureResolution: PSize? = nil
  var cropRegion: PRect? = nil
  var initialSettings: CameraSettings? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenConfiguration? {
    let cameraId: String? = nilOrValue(pigeonVar_list[0])
    let captureResolution: PSize? = nilOrValue(pigeonVar_list[1])
    let cropRegion: PRect? = nilOrValue(pigeonVar_list[2])
    let initialSettings: CameraSettings? = nilOrValue(pigeonVar_list[3])

    return OpenConfiguration(
      cameraId: cameraId,
      captureResolution: captureResolution,
      cropRegion: cropRegion,
      initialSettings: initialSettings
    )
  }
  func toList() -> [Any?] {
    return [
      cameraId,
      captureResolution,
      cropRegion,
      initialSettings,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionCapabilities {
  var supportedSizes: [PSize?]
  var previewTextureId: Int64
  var activeCaptureResolution: PSize
  var activeCropRegion: PRect
  var streamPixelFormat: String
  var isoMin: Double
  var isoMax: Double
  var exposureDurationMinNs: Int64
  var exposureDurationMaxNs: Int64
  var focusMin: Double
  var focusMax: Double
  var zoomMin: Double
  var zoomMax: Double
  var evMin: Double
  var evMax: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionCapabilities? {
    let supportedSizes = pigeonVar_list[0] as! [PSize?]
    let previewTextureId = pigeonVar_list[1] as! Int64
    let activeCaptureResolution = pigeonVar_list[2] as! PSize
    let activeCropRegion = pigeonVar_list[3] as! PRect
    let streamPixelFormat = pigeonVar_list[4] as! String
    let isoMin = pigeonVar_list[5] as! Double
    let isoMax = pigeonVar_list[6] as! Double
    let exposureDurationMinNs = pigeonVar_list[7] as! Int64
    let exposureDurationMaxNs = pigeonVar_list[8] as! Int64
    let focusMin = pigeonVar_list[9] as! Double
    let focusMax = pigeonVar_list[10] as! Double
    let zoomMin = pigeonVar_list[11] as! Double
    let zoomMax = pigeonVar_list[12] as! Double
    let evMin = pigeonVar_list[13] as! Double
    let evMax = pigeonVar_list[14] as! Double

    return SessionCapabilities(
      supportedSizes: supportedSizes,
      previewTextureId: previewTextureId,
      activeCaptureResolution: activeCaptureResolution,
      activeCropRegion: activeCropRegion,
      streamPixelFormat: streamPixelFormat,
      isoMin: isoMin,
      isoMax: isoMax,
      exposureDurationMinNs: exposureDurationMinNs,
      exposureDurationMaxNs: exposureDurationMaxNs,
      focusMin: focusMin,
      focusMax: focusMax,
      zoomMin: zoomMin,
      zoomMax: zoomMax,
      evMin: evMin,
      evMax: evMax
    )
  }
  func toList() -> [Any?] {
    return [
      supportedSizes,
      previewTextureId,
      activeCaptureResolution,
      activeCropRegion,
      streamPixelFormat,
      isoMin,
      isoMax,
      exposureDurationMinNs,
      exposureDurationMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evMin,
      evMax,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CameraSettings {
  var isoMode: CameraMode? = nil
  var iso: Int64? = nil
  var exposureMode: CameraMode? = nil
  var exposureTimeNs: Int64? = nil
  var focusMode: CameraMode? = nil
  var focusDistance: Double? = nil
  var wbMode: WhiteBalanceMode? = nil
  var wbGainR: Double? = nil
  var wbGainG: Double? = nil
  var wbGainB: Double? = nil
  var zoomRatio: Double? = nil
  var evCompensation: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraSettings? {
    let isoMode: CameraMode? = nilOrValue(pigeonVar_list[0])
    let iso: Int64? = nilOrValue(pigeonVar_list[1])
    let exposureMode: CameraMode? = nilOrValue(pigeonVar_list[2])
    let exposureTimeNs: Int64? = nilOrValue(pigeonVar_list[3])
    let focusMode: CameraMode? = nilOrValue(pigeonVar_list[4])
    let focusDistance: Double? = nilOrValue(pigeonVar_list[5])
    let wbMode: WhiteBalanceMode? = nilOrValue(pigeonVar_list[6])
    let wbGainR: Double? = nilOrValue(pigeonVar_list[7])
    let wbGainG: Double? = nilOrValue(pigeonVar_list[8])
    let wbGainB: Double? = nilOrValue(pigeonVar_list[9])
    let zoomRatio: Double? = nilOrValue(pigeonVar_list[10])
    let evCompensation: Int64? = nilOrValue(pigeonVar_list[11])

    return CameraSettings(
      isoMode: isoMode,
      iso: iso,
      exposureMode: exposureMode,
      exposureTimeNs: exposureTimeNs,
      focusMode: focusMode,
      focusDistance: focusDistance,
      wbMode: wbMode,
      wbGainR: wbGainR,
      wbGainG: wbGainG,
      wbGainB: wbGainB,
      zoomRatio: zoomRatio,
      evCompensation: evCompensation
    )
  }
  func toList() -> [Any?] {
    return [
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistance,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      evCompensation,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProcessingParameters {
  var brightness: Double
  var contrast: Double
  var saturation: Double
  var gamma: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProcessingParameters? {
    let brightness = pigeonVar_list[0] as! Double
    let contrast = pigeonVar_list[1] as! Double
    let saturation = pigeonVar_list[2] as! Double
    let gamma = pigeonVar_list[3] as! Double

    return ProcessingParameters(
      brightness: brightness,
      contrast: contrast,
      saturation: saturation,
      gamma: gamma
    )
  }
  func toList() -> [Any?] {
    return [
      brightness,
      contrast,
      saturation,
      gamma,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StreamConfiguration {
  var activeCaptureResolution: PSize
  var activeCropRegion: PRect


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StreamConfiguration? {
    let activeCaptureResolution = pigeonVar_list[0] as! PSize
    let activeCropRegion = pigeonVar_list[1] as! PRect

    return StreamConfiguration(
      activeCaptureResolution: activeCaptureResolution,
      activeCropRegion: activeCropRegion
    )
  }
  func toList() -> [Any?] {
    return [
      activeCaptureResolution,
      activeCropRegion,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FrameResult {
  var iso: Int64? = nil
  var exposureTimeNs: Int64? = nil
  var focusDistance: Double? = nil
  var wbGainR: Double? = nil
  var wbGainG: Double? = nil
  var wbGainB: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FrameResult? {
    let iso: Int64? = nilOrValue(pigeonVar_list[0])
    let exposureTimeNs: Int64? = nilOrValue(pigeonVar_list[1])
    let focusDistance: Double? = nilOrValue(pigeonVar_list[2])
    let wbGainR: Double? = nilOrValue(pigeonVar_list[3])
    let wbGainG: Double? = nilOrValue(pigeonVar_list[4])
    let wbGainB: Double? = nilOrValue(pigeonVar_list[5])

    return FrameResult(
      iso: iso,
      exposureTimeNs: exposureTimeNs,
      focusDistance: focusDistance,
      wbGainR: wbGainR,
      wbGainG: wbGainG,
      wbGainB: wbGainB
    )
  }
  func toList() -> [Any?] {
    return [
      iso,
      exposureTimeNs,
      focusDistance,
      wbGainR,
      wbGainG,
      wbGainB,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecordingOptions {
  var bitrateBps: Int64? = nil
  var fps: Int64? = nil
  var outputPath: String? = nil
  var photosDestination: PhotosDestination


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecordingOptions? {
    let bitrateBps: Int64? = nilOrValue(pigeonVar_list[0])
    let fps: Int64? = nilOrValue(pigeonVar_list[1])
    let outputPath: String? = nilOrValue(pigeonVar_list[2])
    let photosDestination = pigeonVar_list[3] as! PhotosDestination

    return RecordingOptions(
      bitrateBps: bitrateBps,
      fps: fps,
      outputPath: outputPath,
      photosDestination: photosDestination
    )
  }
  func toList() -> [Any?] {
    return [
      bitrateBps,
      fps,
      outputPath,
      photosDestination,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecordingStart {
  var uri: String
  var displayName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecordingStart? {
    let uri = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String

    return RecordingStart(
      uri: uri,
      displayName: displayName
    )
  }
  func toList() -> [Any?] {
    return [
      uri,
      displayName,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecordingStateValue {
  var kind: RecordingStateKind
  var lastUri: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecordingStateValue? {
    let kind = pigeonVar_list[0] as! RecordingStateKind
    let lastUri: String? = nilOrValue(pigeonVar_list[1])

    return RecordingStateValue(
      kind: kind,
      lastUri: lastUri
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      lastUri,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RgbSample {
  var r: Double
  var g: Double
  var b: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RgbSample? {
    let r = pigeonVar_list[0] as! Double
    let g = pigeonVar_list[1] as! Double
    let b = pigeonVar_list[2] as! Double

    return RgbSample(
      r: r,
      g: g,
      b: b
    )
  }
  func toList() -> [Any?] {
    return [
      r,
      g,
      b,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CalibrationResult {
  var before: RgbSample
  var after: RgbSample
  var converged: Bool
  var iterations: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CalibrationResult? {
    let before = pigeonVar_list[0] as! RgbSample
    let after = pigeonVar_list[1] as! RgbSample
    let converged = pigeonVar_list[2] as! Bool
    let iterations = pigeonVar_list[3] as! Int64

    return CalibrationResult(
      before: before,
      after: after,
      converged: converged,
      iterations: iterations
    )
  }
  func toList() -> [Any?] {
    return [
      before,
      after,
      converged,
      iterations,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CameraError {
  var code: CameraErrorCode
  var message: String
  var isFatal: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraError? {
    let code = pigeonVar_list[0] as! CameraErrorCode
    let message = pigeonVar_list[1] as! String
    let isFatal = pigeonVar_list[2] as! Bool

    return CameraError(
      code: code,
      message: message,
      isFatal: isFatal
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      isFatal,
    ]
  }
}

private class CambrianIosCameraApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SessionState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return StreamId(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraPermissionStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PhotosDestination(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraMode(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WhiteBalanceMode(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RecordingStateKind(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      return PSize.fromList(self.readValue() as! [Any?])
    case 138:
      return PRect.fromList(self.readValue() as! [Any?])
    case 139:
      return OpenConfiguration.fromList(self.readValue() as! [Any?])
    case 140:
      return SessionCapabilities.fromList(self.readValue() as! [Any?])
    case 141:
      return CameraSettings.fromList(self.readValue() as! [Any?])
    case 142:
      return ProcessingParameters.fromList(self.readValue() as! [Any?])
    case 143:
      return StreamConfiguration.fromList(self.readValue() as! [Any?])
    case 144:
      return FrameResult.fromList(self.readValue() as! [Any?])
    case 145:
      return RecordingOptions.fromList(self.readValue() as! [Any?])
    case 146:
      return RecordingStart.fromList(self.readValue() as! [Any?])
    case 147:
      return RecordingStateValue.fromList(self.readValue() as! [Any?])
    case 148:
      return RgbSample.fromList(self.readValue() as! [Any?])
    case 149:
      return CalibrationResult.fromList(self.readValue() as! [Any?])
    case 150:
      return CameraError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CambrianIosCameraApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SessionState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? StreamId {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraPermissionStatus {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PhotosDestination {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraMode {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? WhiteBalanceMode {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? RecordingStateKind {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraErrorCode {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? PSize {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PRect {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? OpenConfiguration {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? SessionCapabilities {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? CameraSettings {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ProcessingParameters {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? StreamConfiguration {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? FrameResult {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? RecordingOptions {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? RecordingStart {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? RecordingStateValue {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? RgbSample {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? CalibrationResult {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? CameraError {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CambrianIosCameraApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CambrianIosCameraApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CambrianIosCameraApiPigeonCodecWriter(data: data)
  }
}

class CambrianIosCameraApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CambrianIosCameraApiPigeonCodec(readerWriter: CambrianIosCameraApiPigeonCodecReaderWriter())
}

var cambrianIosCameraApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: CambrianIosCameraApiPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraEngineHostApi {
  func open(configuration: OpenConfiguration?, completion: @escaping (Result<SessionCapabilities, Error>) -> Void)
  func close(completion: @escaping (Result<Void, Error>) -> Void)
  func currentState(completion: @escaping (Result<SessionState, Error>) -> Void)
  func currentSettings(completion: @escaping (Result<CameraSettings?, Error>) -> Void)
  func currentProcessingParameters(completion: @escaping (Result<ProcessingParameters?, Error>) -> Void)
  func updateSettings(settings: CameraSettings, completion: @escaping (Result<Void, Error>) -> Void)
  func setResolution(size: PSize, completion: @escaping (Result<Void, Error>) -> Void)
  func setProcessingParams(params: ProcessingParameters, completion: @escaping (Result<Void, Error>) -> Void)
  func setCropRegion(rect: PRect, completion: @escaping (Result<Void, Error>) -> Void)
  func captureImage(outputPath: String?, photosDestination: PhotosDestination, completion: @escaping (Result<String, Error>) -> Void)
  func captureNaturalPicture(outputPath: String?, photosDestination: PhotosDestination, completion: @escaping (Result<String, Error>) -> Void)
  func startRecording(options: RecordingOptions, completion: @escaping (Result<RecordingStart, Error>) -> Void)
  func stopRecording(completion: @escaping (Result<String, Error>) -> Void)
  func calibrateWhiteBalance(completion: @escaping (Result<CalibrationResult, Error>) -> Void)
  /// Calibrate the linear black point from a dark field. Returns nothing on
  /// success; throws (CameraErrorCode.calibrationFailed) when the field isn't
  /// dark enough. Replaces the removed calibrateBlackBalance.
  func calibrateBlackPoint(completion: @escaping (Result<Void, Error>) -> Void)
  func createPreviewTexture(stream: StreamId, completion: @escaping (Result<Int64, Error>) -> Void)
  func destroyPreviewTexture(textureId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraEngineHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CambrianIosCameraApiPigeonCodec.shared }
  /// Sets up an instance of `CameraEngineHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraEngineHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg: OpenConfiguration? = nilOrValue(args[0])
        api.open(configuration: configurationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { _, reply in
        api.close { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
    let currentStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentStateChannel.setMessageHandler { _, reply in
        api.currentState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      currentStateChannel.setMessageHandler(nil)
    }
    let currentSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentSettingsChannel.setMessageHandler { _, reply in
        api.currentSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      currentSettingsChannel.setMessageHandler(nil)
    }
    let currentProcessingParametersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentProcessingParameters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentProcessingParametersChannel.setMessageHandler { _, reply in
        api.currentProcessingParameters { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      currentProcessingParametersChannel.setMessageHandler(nil)
    }
    let updateSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.updateSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! CameraSettings
        api.updateSettings(settings: settingsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateSettingsChannel.setMessageHandler(nil)
    }
    let setResolutionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setResolution\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setResolutionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sizeArg = args[0] as! PSize
        api.setResolution(size: sizeArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setResolutionChannel.setMessageHandler(nil)
    }
    let setProcessingParamsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setProcessingParams\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProcessingParamsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! ProcessingParameters
        api.setProcessingParams(params: paramsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setProcessingParamsChannel.setMessageHandler(nil)
    }
    let setCropRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setCropRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCropRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rectArg = args[0] as! PRect
        api.setCropRegion(rect: rectArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setCropRegionChannel.setMessageHandler(nil)
    }
    let captureImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.captureImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let outputPathArg: String? = nilOrValue(args[0])
        let photosDestinationArg = args[1] as! PhotosDestination
        api.captureImage(outputPath: outputPathArg, photosDestination: photosDestinationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      captureImageChannel.setMessageHandler(nil)
    }
    let captureNaturalPictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.captureNaturalPicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureNaturalPictureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let outputPathArg: String? = nilOrValue(args[0])
        let photosDestinationArg = args[1] as! PhotosDestination
        api.captureNaturalPicture(outputPath: outputPathArg, photosDestination: photosDestinationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      captureNaturalPictureChannel.setMessageHandler(nil)
    }
    let startRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.startRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRecordingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! RecordingOptions
        api.startRecording(options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startRecordingChannel.setMessageHandler(nil)
    }
    let stopRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.stopRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRecordingChannel.setMessageHandler { _, reply in
        api.stopRecording { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopRecordingChannel.setMessageHandler(nil)
    }
    let calibrateWhiteBalanceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.calibrateWhiteBalance\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      calibrateWhiteBalanceChannel.setMessageHandler { _, reply in
        api.calibrateWhiteBalance { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      calibrateWhiteBalanceChannel.setMessageHandler(nil)
    }
    /// Calibrate the linear black point from a dark field. Returns nothing on
    /// success; throws (CameraErrorCode.calibrationFailed) when the field isn't
    /// dark enough. Replaces the removed calibrateBlackBalance.
    let calibrateBlackPointChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.calibrateBlackPoint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      calibrateBlackPointChannel.setMessageHandler { _, reply in
        api.calibrateBlackPoint { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      calibrateBlackPointChannel.setMessageHandler(nil)
    }
    let createPreviewTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.createPreviewTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createPreviewTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let streamArg = args[0] as! StreamId
        api.createPreviewTexture(stream: streamArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createPreviewTextureChannel.setMessageHandler(nil)
    }
    let destroyPreviewTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.destroyPreviewTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyPreviewTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textureIdArg = args[0] as! Int64
        api.destroyPreviewTexture(textureId: textureIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      destroyPreviewTextureChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PermissionsHostApi {
  func cameraPermissionStatus(completion: @escaping (Result<CameraPermissionStatus, Error>) -> Void)
  func requestCameraPermission(completion: @escaping (Result<CameraPermissionStatus, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PermissionsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CambrianIosCameraApiPigeonCodec.shared }
  /// Sets up an instance of `PermissionsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PermissionsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let cameraPermissionStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.PermissionsHostApi.cameraPermissionStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cameraPermissionStatusChannel.setMessageHandler { _, reply in
        api.cameraPermissionStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cameraPermissionStatusChannel.setMessageHandler(nil)
    }
    let requestCameraPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_ios_camera.PermissionsHostApi.requestCameraPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCameraPermissionChannel.setMessageHandler { _, reply in
        api.requestCameraPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCameraPermissionChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class StreamStateStreamHandler: PigeonEventChannelWrapper<SessionState> {
  static func register(with messenger: FlutterBinaryMessenger, 
                      instanceName: String = "",
                      streamHandler: StreamStateStreamHandler) {
    var channelName = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamState"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<SessionState>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: cambrianIosCameraApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class StreamErrorsStreamHandler: PigeonEventChannelWrapper<CameraError> {
  static func register(with messenger: FlutterBinaryMessenger, 
                      instanceName: String = "",
                      streamHandler: StreamErrorsStreamHandler) {
    var channelName = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamErrors"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<CameraError>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: cambrianIosCameraApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class StreamStreamConfigurationsStreamHandler: PigeonEventChannelWrapper<StreamConfiguration> {
  static func register(with messenger: FlutterBinaryMessenger, 
                      instanceName: String = "",
                      streamHandler: StreamStreamConfigurationsStreamHandler) {
    var channelName = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamStreamConfigurations"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<StreamConfiguration>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: cambrianIosCameraApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class StreamFrameResultsStreamHandler: PigeonEventChannelWrapper<FrameResult> {
  static func register(with messenger: FlutterBinaryMessenger, 
                      instanceName: String = "",
                      streamHandler: StreamFrameResultsStreamHandler) {
    var channelName = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamFrameResults"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<FrameResult>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: cambrianIosCameraApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class StreamRecordingStatesStreamHandler: PigeonEventChannelWrapper<RecordingStateValue> {
  static func register(with messenger: FlutterBinaryMessenger, 
                      instanceName: String = "",
                      streamHandler: StreamRecordingStatesStreamHandler) {
    var channelName = "dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamRecordingStates"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<RecordingStateValue>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: cambrianIosCameraApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
