// Mocks generated by Mockito 5.4.6 from annotations
// in cambrian_ios_camera/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cambrian_ios_camera/src/pigeon/cambrian_ios_camera_api.g.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSessionCapabilities_0 extends _i1.SmartFake
    implements _i2.SessionCapabilities {
  _FakeSessionCapabilities_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecordingStart_1 extends _i1.SmartFake
    implements _i2.RecordingStart {
  _FakeRecordingStart_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCalibrationResult_2 extends _i1.SmartFake
    implements _i2.CalibrationResult {
  _FakeCalibrationResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CameraEngineHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraEngineHostApi extends _i1.Mock
    implements _i2.CameraEngineHostApi {
  MockCameraEngineHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix => (super.noSuchMethod(
        Invocation.getter(#pigeonVar_messageChannelSuffix),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#pigeonVar_messageChannelSuffix),
        ),
      ) as String);

  @override
  _i4.Future<_i2.SessionCapabilities> open(
          _i2.OpenConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [configuration],
        ),
        returnValue: _i4.Future<_i2.SessionCapabilities>.value(
            _FakeSessionCapabilities_0(
          this,
          Invocation.method(
            #open,
            [configuration],
          ),
        )),
      ) as _i4.Future<_i2.SessionCapabilities>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.CameraSettings?> currentSettings() => (super.noSuchMethod(
        Invocation.method(
          #currentSettings,
          [],
        ),
        returnValue: _i4.Future<_i2.CameraSettings?>.value(),
      ) as _i4.Future<_i2.CameraSettings?>);

  @override
  _i4.Future<_i2.ProcessingParameters?> currentProcessingParameters() =>
      (super.noSuchMethod(
        Invocation.method(
          #currentProcessingParameters,
          [],
        ),
        returnValue: _i4.Future<_i2.ProcessingParameters?>.value(),
      ) as _i4.Future<_i2.ProcessingParameters?>);

  @override
  _i4.Future<void> updateSettings(_i2.CameraSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [settings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setResolution(_i2.PSize? size) => (super.noSuchMethod(
        Invocation.method(
          #setResolution,
          [size],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setProcessingParams(_i2.ProcessingParameters? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #setProcessingParams,
          [params],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setCropRegion(_i2.PRect? rect) => (super.noSuchMethod(
        Invocation.method(
          #setCropRegion,
          [rect],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> captureImage(
    String? outputPath,
    _i2.PhotosDestination? photosDestination,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureImage,
          [
            outputPath,
            photosDestination,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #captureImage,
            [
              outputPath,
              photosDestination,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> captureNaturalPicture(
    String? outputPath,
    _i2.PhotosDestination? photosDestination,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureNaturalPicture,
          [
            outputPath,
            photosDestination,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #captureNaturalPicture,
            [
              outputPath,
              photosDestination,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.RecordingStart> startRecording(
          _i2.RecordingOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [options],
        ),
        returnValue: _i4.Future<_i2.RecordingStart>.value(_FakeRecordingStart_1(
          this,
          Invocation.method(
            #startRecording,
            [options],
          ),
        )),
      ) as _i4.Future<_i2.RecordingStart>);

  @override
  _i4.Future<String> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #stopRecording,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.CalibrationResult> calibrateWhiteBalance() =>
      (super.noSuchMethod(
        Invocation.method(
          #calibrateWhiteBalance,
          [],
        ),
        returnValue:
            _i4.Future<_i2.CalibrationResult>.value(_FakeCalibrationResult_2(
          this,
          Invocation.method(
            #calibrateWhiteBalance,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CalibrationResult>);

  @override
  _i4.Future<_i2.CalibrationResult> calibrateBlackBalance() =>
      (super.noSuchMethod(
        Invocation.method(
          #calibrateBlackBalance,
          [],
        ),
        returnValue:
            _i4.Future<_i2.CalibrationResult>.value(_FakeCalibrationResult_2(
          this,
          Invocation.method(
            #calibrateBlackBalance,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CalibrationResult>);

  @override
  _i4.Future<int> createPreviewTexture(_i2.StreamId? stream) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPreviewTexture,
          [stream],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> destroyPreviewTexture(int? textureId) => (super.noSuchMethod(
        Invocation.method(
          #destroyPreviewTexture,
          [textureId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PermissionsHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsHostApi extends _i1.Mock
    implements _i2.PermissionsHostApi {
  MockPermissionsHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix => (super.noSuchMethod(
        Invocation.getter(#pigeonVar_messageChannelSuffix),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#pigeonVar_messageChannelSuffix),
        ),
      ) as String);

  @override
  _i4.Future<_i2.CameraPermissionStatus> cameraPermissionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #cameraPermissionStatus,
          [],
        ),
        returnValue: _i4.Future<_i2.CameraPermissionStatus>.value(
            _i2.CameraPermissionStatus.notDetermined),
      ) as _i4.Future<_i2.CameraPermissionStatus>);

  @override
  _i4.Future<_i2.CameraPermissionStatus> requestCameraPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestCameraPermission,
          [],
        ),
        returnValue: _i4.Future<_i2.CameraPermissionStatus>.value(
            _i2.CameraPermissionStatus.notDetermined),
      ) as _i4.Future<_i2.CameraPermissionStatus>);
}
