#!/usr/bin/env bash
# regen-contracts.sh — full regeneration of CameraKit/CONTRACTS.md.
#
# v1 strategy: use repomix --compress --remove-comments on CameraKit/Sources/,
# post-filter to public API only, append scaffold inventory + isolation diagram.
#
# v2 candidate (see plan): switch to `.swiftinterface` files emitted via
# -emit-module-interface in Package.swift swiftSettings.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/CameraKit/CONTRACTS.md"
TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

cd "$REPO_ROOT"

if ! command -v repomix >/dev/null 2>&1; then
  echo "repomix not found; install with: brew install repomix" >&2
  exit 2
fi

# 1. Generate a compressed snapshot of the library sources.
#    --no-file-summary / --no-directory-structure strip repomix's boilerplate
#    so we keep only the "## File: path" + compressed code sections.
repomix \
  --include 'CameraKit/Sources/CameraKit/**/*.swift' \
  --compress \
  --remove-comments \
  --style markdown \
  --no-file-summary \
  --no-directory-structure \
  --output "$TMP/sources.md" \
  --quiet

# 2. Generate the scaffold inventory as a markdown table.
SCAFFOLDS=$("$REPO_ROOT/scripts/scaffold-inventory.sh" CameraKit/Sources/)

# 3. Assemble CONTRACTS.md.
{
  cat <<EOF
# CONTRACTS.md — CameraKit current shape

> Auto-generated by \`scripts/regen-contracts.sh\`; regenerated by lefthook's
> pre-commit hook. Do not edit by hand; changes will be overwritten. Source of
> truth is the swift files under \`CameraKit/Sources/CameraKit/\`. (No timestamp
> here on purpose — it must be byte-deterministic so the pre-commit gate only
> fires on real API-shape changes; git history records when it changed.)

## Active scaffolds

$SCAFFOLDS

## Compressed source snapshot

EOF
  # Keep from the "# Files" header onward, then sort the per-file "## File:"
  # blocks alphabetically by path. repomix emits sections in an unstable
  # (mtime-derived) order, which produced large spurious reorder diffs on every
  # commit; sorting makes the snapshot deterministic so diffs reflect real
  # contract changes only. (requires perl ≥ 5.10 for -0777 + lookahead split.)
  perl -0777 -ne '
    next unless /^(.*?# Files\n)(.*)$/s;
    my ($head, $rest) = ($1, $2);
    my @parts  = split /(?=^## File: )/m, $rest;
    my @blocks = grep {  /^## File: / } @parts;
    my ($pre)  = grep { !/^## File: / } @parts;
    print $head;
    print $pre if defined $pre;
    print sort {
      my ($pa) = $a =~ m{^## File: (\S+)};
      my ($pb) = $b =~ m{^## File: (\S+)};
      $pa cmp $pb
    } @blocks;
  ' "$TMP/sources.md"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
