#!/usr/bin/env bash
# regen-contracts.sh — full regeneration of CameraKit/CONTRACTS.md.
#
# v1 strategy: use repomix --compress --remove-comments on CameraKit/Sources/,
# post-filter to public API only, append scaffold inventory + isolation diagram.
#
# v2 candidate (see plan): switch to `.swiftinterface` files emitted via
# -emit-module-interface in Package.swift swiftSettings.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/CameraKit/CONTRACTS.md"
TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

cd "$REPO_ROOT"

if ! command -v repomix >/dev/null 2>&1; then
  echo "repomix not found; install with: brew install repomix" >&2
  exit 2
fi

# 1. Generate a compressed snapshot of the library sources.
#    --no-file-summary / --no-directory-structure strip repomix's boilerplate
#    so we keep only the "## File: path" + compressed code sections.
repomix \
  --include 'CameraKit/Sources/CameraKit/**/*.swift' \
  --compress \
  --remove-comments \
  --style markdown \
  --no-file-summary \
  --no-directory-structure \
  --output "$TMP/sources.md" \
  --quiet

# 2. Generate the scaffold inventory as a markdown table.
SCAFFOLDS=$("$REPO_ROOT/scripts/scaffold-inventory.sh" CameraKit/Sources/)

# 3. Assemble CONTRACTS.md.
{
  cat <<EOF
# CONTRACTS.md — CameraKit current shape

> Auto-generated by \`scripts/regen-contracts.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC').
> Do not edit by hand; changes will be overwritten. Source of truth is the
> swift files under \`CameraKit/Sources/CameraKit/\`.

## Active scaffolds

$SCAFFOLDS

## Compressed source snapshot

EOF
  # Strip leading blank lines / any residual summary, keep from first "# Files" header.
  sed -n '/^# Files$/,$p' "$TMP/sources.md"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
