// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum SessionState {
  opening,
  streaming,
  recovering,
  paused,
  error,
  closed,
  interrupted,
}

enum StreamId {
  primary,
  tracker,
}

enum CameraPermissionStatus {
  notDetermined,
  denied,
  restricted,
  authorized,
}

enum PhotosDestination {
  none,
  copy,
  move,
}

enum CameraMode {
  auto,
  manual,
}

enum WhiteBalanceMode {
  auto,
  locked,
  manual,
}

enum RecordingStateKind {
  idle,
  recording,
  finalizing,
}

enum CameraErrorCode {
  cameraNotFound,
  cameraInUse,
  permissionDenied,
  cameraAccessError,
  cameraDisconnected,
  configurationFailed,
  captureFailure,
  recordingStartFailed,
  recordingFailed,
  recordingTruncated,
  frameStall,
  maxRetriesExceeded,
  unknownError,
  settingsConflict,
  invalidFormat,
  fpsDegraded,
  aeConvergenceTimeout,
  invalidState,
  hardwareError,
  notOpen,
  calibrationFailed,
}

class PSize {
  PSize({
    required this.width,
    required this.height,
  });

  int width;

  int height;

  Object encode() {
    return <Object?>[
      width,
      height,
    ];
  }

  static PSize decode(Object result) {
    result as List<Object?>;
    return PSize(
      width: result[0]! as int,
      height: result[1]! as int,
    );
  }
}

class PRect {
  PRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  int x;

  int y;

  int width;

  int height;

  Object encode() {
    return <Object?>[
      x,
      y,
      width,
      height,
    ];
  }

  static PRect decode(Object result) {
    result as List<Object?>;
    return PRect(
      x: result[0]! as int,
      y: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
    );
  }
}

class OpenConfiguration {
  OpenConfiguration({
    this.cameraId,
    this.captureResolution,
    this.targetFps,
    this.cropRegion,
    this.initialSettings,
  });

  String? cameraId;

  PSize? captureResolution;

  /// Target capture frame rate, locked in every mode. `null` → the default (30).
  ///
  /// Validated at open against the selected resolution's supported ranges
  /// (see [SessionCapabilities.supportedFrameRates]); an unsupported
  /// `(captureResolution, targetFps)` pair fails the open with a configuration error.
  int? targetFps;

  PRect? cropRegion;

  CameraSettings? initialSettings;

  Object encode() {
    return <Object?>[
      cameraId,
      captureResolution,
      targetFps,
      cropRegion,
      initialSettings,
    ];
  }

  static OpenConfiguration decode(Object result) {
    result as List<Object?>;
    return OpenConfiguration(
      cameraId: result[0] as String?,
      captureResolution: result[1] as PSize?,
      targetFps: result[2] as int?,
      cropRegion: result[3] as PRect?,
      initialSettings: result[4] as CameraSettings?,
    );
  }
}

/// A capture resolution paired with a frame-rate range it supports.
///
/// One entry per (size, supported range); a size can appear more than once (e.g. a
/// full-FOV 1–60 range and a binned 2–240 slow-mo range). Mirror of CameraKit
/// `FrameRateRange`.
class PFrameRateRange {
  PFrameRateRange({
    required this.size,
    required this.minFps,
    required this.maxFps,
  });

  PSize size;

  int minFps;

  int maxFps;

  Object encode() {
    return <Object?>[
      size,
      minFps,
      maxFps,
    ];
  }

  static PFrameRateRange decode(Object result) {
    result as List<Object?>;
    return PFrameRateRange(
      size: result[0]! as PSize,
      minFps: result[1]! as int,
      maxFps: result[2]! as int,
    );
  }
}

class SessionCapabilities {
  SessionCapabilities({
    required this.supportedSizes,
    required this.supportedFrameRates,
    required this.activeFrameRate,
    required this.activeCaptureResolution,
    required this.activeCropRegion,
    required this.streamPixelFormat,
    required this.isoMin,
    required this.isoMax,
    required this.exposureDurationMinNs,
    required this.exposureDurationMaxNs,
    required this.focusMin,
    required this.focusMax,
    required this.zoomMin,
    required this.zoomMax,
    required this.evMin,
    required this.evMax,
  });

  List<PSize?> supportedSizes;

  /// Frame-rate ranges supported per resolution (live device data, incl. slow-mo).
  /// A caller reads this to pick a valid `(captureResolution, targetFps)`.
  List<PFrameRateRange?> supportedFrameRates;

  /// The frame rate the session is locked to (the resolved [OpenConfiguration.targetFps]).
  int activeFrameRate;

  PSize activeCaptureResolution;

  PRect activeCropRegion;

  String streamPixelFormat;

  double isoMin;

  double isoMax;

  int exposureDurationMinNs;

  int exposureDurationMaxNs;

  double focusMin;

  double focusMax;

  double zoomMin;

  double zoomMax;

  double evMin;

  double evMax;

  Object encode() {
    return <Object?>[
      supportedSizes,
      supportedFrameRates,
      activeFrameRate,
      activeCaptureResolution,
      activeCropRegion,
      streamPixelFormat,
      isoMin,
      isoMax,
      exposureDurationMinNs,
      exposureDurationMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evMin,
      evMax,
    ];
  }

  static SessionCapabilities decode(Object result) {
    result as List<Object?>;
    return SessionCapabilities(
      supportedSizes: (result[0] as List<Object?>?)!.cast<PSize?>(),
      supportedFrameRates: (result[1] as List<Object?>?)!.cast<PFrameRateRange?>(),
      activeFrameRate: result[2]! as int,
      activeCaptureResolution: result[3]! as PSize,
      activeCropRegion: result[4]! as PRect,
      streamPixelFormat: result[5]! as String,
      isoMin: result[6]! as double,
      isoMax: result[7]! as double,
      exposureDurationMinNs: result[8]! as int,
      exposureDurationMaxNs: result[9]! as int,
      focusMin: result[10]! as double,
      focusMax: result[11]! as double,
      zoomMin: result[12]! as double,
      zoomMax: result[13]! as double,
      evMin: result[14]! as double,
      evMax: result[15]! as double,
    );
  }
}

class CameraSettings {
  CameraSettings({
    this.isoMode,
    this.iso,
    this.exposureMode,
    this.exposureTimeNs,
    this.focusMode,
    this.focusDistance,
    this.wbMode,
    this.wbGainR,
    this.wbGainG,
    this.wbGainB,
    this.zoomRatio,
    this.evCompensation,
  });

  CameraMode? isoMode;

  int? iso;

  CameraMode? exposureMode;

  int? exposureTimeNs;

  CameraMode? focusMode;

  double? focusDistance;

  WhiteBalanceMode? wbMode;

  double? wbGainR;

  double? wbGainG;

  double? wbGainB;

  double? zoomRatio;

  int? evCompensation;

  Object encode() {
    return <Object?>[
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistance,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      evCompensation,
    ];
  }

  static CameraSettings decode(Object result) {
    result as List<Object?>;
    return CameraSettings(
      isoMode: result[0] as CameraMode?,
      iso: result[1] as int?,
      exposureMode: result[2] as CameraMode?,
      exposureTimeNs: result[3] as int?,
      focusMode: result[4] as CameraMode?,
      focusDistance: result[5] as double?,
      wbMode: result[6] as WhiteBalanceMode?,
      wbGainR: result[7] as double?,
      wbGainG: result[8] as double?,
      wbGainB: result[9] as double?,
      zoomRatio: result[10] as double?,
      evCompensation: result[11] as int?,
    );
  }
}

class ProcessingParameters {
  ProcessingParameters({
    required this.brightness,
    required this.contrast,
    required this.saturation,
    required this.gamma,
  });

  double brightness;

  double contrast;

  double saturation;

  double gamma;

  Object encode() {
    return <Object?>[
      brightness,
      contrast,
      saturation,
      gamma,
    ];
  }

  static ProcessingParameters decode(Object result) {
    result as List<Object?>;
    return ProcessingParameters(
      brightness: result[0]! as double,
      contrast: result[1]! as double,
      saturation: result[2]! as double,
      gamma: result[3]! as double,
    );
  }
}

class StreamConfiguration {
  StreamConfiguration({
    required this.activeCaptureResolution,
    required this.activeCropRegion,
  });

  PSize activeCaptureResolution;

  PRect activeCropRegion;

  Object encode() {
    return <Object?>[
      activeCaptureResolution,
      activeCropRegion,
    ];
  }

  static StreamConfiguration decode(Object result) {
    result as List<Object?>;
    return StreamConfiguration(
      activeCaptureResolution: result[0]! as PSize,
      activeCropRegion: result[1]! as PRect,
    );
  }
}

class FrameResult {
  FrameResult({
    this.iso,
    this.exposureTimeNs,
    this.focusDistance,
    this.wbGainR,
    this.wbGainG,
    this.wbGainB,
  });

  int? iso;

  int? exposureTimeNs;

  double? focusDistance;

  double? wbGainR;

  double? wbGainG;

  double? wbGainB;

  Object encode() {
    return <Object?>[
      iso,
      exposureTimeNs,
      focusDistance,
      wbGainR,
      wbGainG,
      wbGainB,
    ];
  }

  static FrameResult decode(Object result) {
    result as List<Object?>;
    return FrameResult(
      iso: result[0] as int?,
      exposureTimeNs: result[1] as int?,
      focusDistance: result[2] as double?,
      wbGainR: result[3] as double?,
      wbGainG: result[4] as double?,
      wbGainB: result[5] as double?,
    );
  }
}

class RecordingOptions {
  RecordingOptions({
    this.bitrateBps,
    this.fps,
    this.outputPath,
    required this.photosDestination,
  });

  int? bitrateBps;

  /// Advisory writer frame rate. The *capture* rate is locked to
  /// [OpenConfiguration.targetFps] in every mode (configurable-frame-rate), so a
  /// value here that differs from the session's target does not change the delivered
  /// frame rate; leave it null to track the session frame rate.
  int? fps;

  String? outputPath;

  PhotosDestination photosDestination;

  Object encode() {
    return <Object?>[
      bitrateBps,
      fps,
      outputPath,
      photosDestination,
    ];
  }

  static RecordingOptions decode(Object result) {
    result as List<Object?>;
    return RecordingOptions(
      bitrateBps: result[0] as int?,
      fps: result[1] as int?,
      outputPath: result[2] as String?,
      photosDestination: result[3]! as PhotosDestination,
    );
  }
}

class RecordingStart {
  RecordingStart({
    required this.uri,
    required this.displayName,
  });

  String uri;

  String displayName;

  Object encode() {
    return <Object?>[
      uri,
      displayName,
    ];
  }

  static RecordingStart decode(Object result) {
    result as List<Object?>;
    return RecordingStart(
      uri: result[0]! as String,
      displayName: result[1]! as String,
    );
  }
}

class RecordingStateValue {
  RecordingStateValue({
    required this.kind,
    this.lastUri,
  });

  RecordingStateKind kind;

  String? lastUri;

  Object encode() {
    return <Object?>[
      kind,
      lastUri,
    ];
  }

  static RecordingStateValue decode(Object result) {
    result as List<Object?>;
    return RecordingStateValue(
      kind: result[0]! as RecordingStateKind,
      lastUri: result[1] as String?,
    );
  }
}

class RgbSample {
  RgbSample({
    required this.r,
    required this.g,
    required this.b,
  });

  double r;

  double g;

  double b;

  Object encode() {
    return <Object?>[
      r,
      g,
      b,
    ];
  }

  static RgbSample decode(Object result) {
    result as List<Object?>;
    return RgbSample(
      r: result[0]! as double,
      g: result[1]! as double,
      b: result[2]! as double,
    );
  }
}

class CalibrationResult {
  CalibrationResult({
    required this.before,
    required this.after,
    required this.converged,
    required this.iterations,
  });

  RgbSample before;

  RgbSample after;

  bool converged;

  int iterations;

  Object encode() {
    return <Object?>[
      before,
      after,
      converged,
      iterations,
    ];
  }

  static CalibrationResult decode(Object result) {
    result as List<Object?>;
    return CalibrationResult(
      before: result[0]! as RgbSample,
      after: result[1]! as RgbSample,
      converged: result[2]! as bool,
      iterations: result[3]! as int,
    );
  }
}

class CameraError {
  CameraError({
    required this.code,
    required this.message,
    required this.isFatal,
  });

  CameraErrorCode code;

  String message;

  bool isFatal;

  Object encode() {
    return <Object?>[
      code,
      message,
      isFatal,
    ];
  }

  static CameraError decode(Object result) {
    result as List<Object?>;
    return CameraError(
      code: result[0]! as CameraErrorCode,
      message: result[1]! as String,
      isFatal: result[2]! as bool,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SessionState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is StreamId) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is CameraPermissionStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PhotosDestination) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is CameraMode) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is WhiteBalanceMode) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is RecordingStateKind) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is CameraErrorCode) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is PSize) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is PRect) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is OpenConfiguration) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is PFrameRateRange) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is SessionCapabilities) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is CameraSettings) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is ProcessingParameters) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is StreamConfiguration) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is FrameResult) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is RecordingOptions) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is RecordingStart) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is RecordingStateValue) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is RgbSample) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is CalibrationResult) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is CameraError) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : SessionState.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : StreamId.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CameraPermissionStatus.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PhotosDestination.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CameraMode.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : WhiteBalanceMode.values[value];
      case 135: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RecordingStateKind.values[value];
      case 136: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CameraErrorCode.values[value];
      case 137: 
        return PSize.decode(readValue(buffer)!);
      case 138: 
        return PRect.decode(readValue(buffer)!);
      case 139: 
        return OpenConfiguration.decode(readValue(buffer)!);
      case 140: 
        return PFrameRateRange.decode(readValue(buffer)!);
      case 141: 
        return SessionCapabilities.decode(readValue(buffer)!);
      case 142: 
        return CameraSettings.decode(readValue(buffer)!);
      case 143: 
        return ProcessingParameters.decode(readValue(buffer)!);
      case 144: 
        return StreamConfiguration.decode(readValue(buffer)!);
      case 145: 
        return FrameResult.decode(readValue(buffer)!);
      case 146: 
        return RecordingOptions.decode(readValue(buffer)!);
      case 147: 
        return RecordingStart.decode(readValue(buffer)!);
      case 148: 
        return RecordingStateValue.decode(readValue(buffer)!);
      case 149: 
        return RgbSample.decode(readValue(buffer)!);
      case 150: 
        return CalibrationResult.decode(readValue(buffer)!);
      case 151: 
        return CameraError.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class CameraEngineHostApi {
  /// Constructor for [CameraEngineHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CameraEngineHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<SessionCapabilities> open(OpenConfiguration? configuration) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.open$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[configuration]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SessionCapabilities?)!;
    }
  }

  Future<void> close() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.close$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<SessionState> currentState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SessionState?)!;
    }
  }

  Future<CameraSettings?> currentSettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as CameraSettings?);
    }
  }

  Future<ProcessingParameters?> currentProcessingParameters() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.currentProcessingParameters$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as ProcessingParameters?);
    }
  }

  Future<void> updateSettings(CameraSettings settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.updateSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[settings]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setResolution(PSize size) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setResolution$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[size]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setProcessingParams(ProcessingParameters params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setProcessingParams$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setCropRegion(PRect rect) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.setCropRegion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[rect]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> captureImage(String? outputPath, PhotosDestination photosDestination) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.captureImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[outputPath, photosDestination]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> captureNaturalPicture(String? outputPath, PhotosDestination photosDestination) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.captureNaturalPicture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[outputPath, photosDestination]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<RecordingStart> startRecording(RecordingOptions options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.startRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RecordingStart?)!;
    }
  }

  Future<String> stopRecording() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.stopRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<CalibrationResult> calibrateWhiteBalance(bool whitePoint) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.calibrateWhiteBalance$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[whitePoint]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CalibrationResult?)!;
    }
  }

  /// Calibrate the linear black point from a dark field. Returns nothing on
  /// success; throws (CameraErrorCode.calibrationFailed) when the field isn't
  /// dark enough. Replaces the removed calibrateBlackBalance.
  Future<void> calibrateBlackPoint() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.calibrateBlackPoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> enableWhiteBalance() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.enableWhiteBalance$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disableWhiteBalance() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.disableWhiteBalance$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> enableWhitePoint() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.enableWhitePoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disableWhitePoint() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.disableWhitePoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> clearWhiteBalance() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.clearWhiteBalance$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> enableBlackPoint() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.enableBlackPoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disableBlackPoint() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.disableBlackPoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> clearBlackPoint() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.clearBlackPoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> createPreviewTexture(StreamId stream) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.createPreviewTexture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[stream]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> destroyPreviewTexture(int textureId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.CameraEngineHostApi.destroyPreviewTexture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[textureId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

class PermissionsHostApi {
  /// Constructor for [PermissionsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PermissionsHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CameraPermissionStatus> cameraPermissionStatus() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.PermissionsHostApi.cameraPermissionStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CameraPermissionStatus?)!;
    }
  }

  Future<CameraPermissionStatus> requestCameraPermission() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_ios_camera.PermissionsHostApi.requestCameraPermission$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CameraPermissionStatus?)!;
    }
  }
}

Stream<SessionState> streamState( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamStateChannel =
      EventChannel('dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamState$instanceName', pigeonMethodCodec);
  return streamStateChannel.receiveBroadcastStream().map((dynamic event) {
    return event as SessionState;
  });
}
    
Stream<CameraError> streamErrors( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamErrorsChannel =
      EventChannel('dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamErrors$instanceName', pigeonMethodCodec);
  return streamErrorsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as CameraError;
  });
}
    
Stream<StreamConfiguration> streamStreamConfigurations( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamStreamConfigurationsChannel =
      EventChannel('dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamStreamConfigurations$instanceName', pigeonMethodCodec);
  return streamStreamConfigurationsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as StreamConfiguration;
  });
}
    
Stream<FrameResult> streamFrameResults( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamFrameResultsChannel =
      EventChannel('dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamFrameResults$instanceName', pigeonMethodCodec);
  return streamFrameResultsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as FrameResult;
  });
}
    
Stream<RecordingStateValue> streamRecordingStates( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamRecordingStatesChannel =
      EventChannel('dev.flutter.pigeon.cambrian_ios_camera.CameraEventApi.streamRecordingStates$instanceName', pigeonMethodCodec);
  return streamRecordingStatesChannel.receiveBroadcastStream().map((dynamic event) {
    return event as RecordingStateValue;
  });
}
    
